services:
  - type: worker
    name: larry-david-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python larry_david_bot.py
    envVars:
      - key: BLUESKY_HANDLE
        sync: false
      - key: BLUESKY_APP_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      # Optional Twitter API credentials
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_SECRET
        sync: false
        sync: false 